# Generated by Django 3.2.6 on 2021-08-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sub_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
